# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class GuaziItem(scrapy.Item):
    # define the fields for your item here like:
    carid = scrapy.Field()
    car_source = scrapy.Field()
    grab_time = scrapy.Field()
    update_time = scrapy.Field()
    post_time = scrapy.Field()
    sold_date = scrapy.Field()
    pagetime = scrapy.Field()
    parsetime = scrapy.Field()
    shortdesc = scrapy.Field()
    pagetitle = scrapy.Field()
    url = scrapy.Field()
    status = scrapy.Field()
    statusplus = scrapy.Field()
    newcarid = scrapy.Field()
    brand = scrapy.Field()
    series = scrapy.Field()
    factoryname = scrapy.Field()
    modelname = scrapy.Field()
    brandid = scrapy.Field()
    familyid = scrapy.Field()
    seriesid = scrapy.Field()
    makeyear = scrapy.Field()
    registeryear = scrapy.Field()
    produceyear = scrapy.Field()
    bodystyle = scrapy.Field()
    level = scrapy.Field()
    fueltype = scrapy.Field()
    driverway = scrapy.Field()
    body = scrapy.Field()
    output = scrapy.Field()
    guideprice = scrapy.Field()
    guidepricetax = scrapy.Field()
    doors = scrapy.Field()
    emission = scrapy.Field()
    gear = scrapy.Field()
    geartype = scrapy.Field()
    seats = scrapy.Field()
    length = scrapy.Field()
    width = scrapy.Field()
    height = scrapy.Field()
    weight = scrapy.Field()
    gearnumber = scrapy.Field()
    wheelbase = scrapy.Field()
    generation = scrapy.Field()
    fuelnumber = scrapy.Field()
    lwv = scrapy.Field()
    lwvnumber = scrapy.Field()
    maxnm = scrapy.Field()
    maxpower = scrapy.Field()
    maxps = scrapy.Field()
    frontgauge = scrapy.Field()
    compress = scrapy.Field()
    registerdate = scrapy.Field()
    years = scrapy.Field()
    paytype = scrapy.Field()
    price1 = scrapy.Field()
    pricetag = scrapy.Field()
    mileage = scrapy.Field()
    usage = scrapy.Field()
    color = scrapy.Field()
    city = scrapy.Field()
    prov = scrapy.Field()
    guarantee = scrapy.Field()
    totalcheck_desc = scrapy.Field()
    totalgrade = scrapy.Field()
    contact_type = scrapy.Field()
    contact_name = scrapy.Field()
    contact_phone = scrapy.Field()
    contact_address = scrapy.Field()
    contact_company = scrapy.Field()
    contact_url = scrapy.Field()
    change_date = scrapy.Field()
    change_times = scrapy.Field()
    insurance1_date = scrapy.Field()
    insurance2_date = scrapy.Field()
    hascheck = scrapy.Field()
    repairinfo = scrapy.Field()
    yearchecktime = scrapy.Field()
    carokcf = scrapy.Field()
    carcard = scrapy.Field()
    carinvoice = scrapy.Field()
    accident_desc = scrapy.Field()
    accident_score = scrapy.Field()
    outer_desc = scrapy.Field()
    outer_score = scrapy.Field()
    inner_desc = scrapy.Field()
    inner_score = scrapy.Field()
    safe_desc = scrapy.Field()
    safe_score = scrapy.Field()
    road_desc = scrapy.Field()
    road_score = scrapy.Field()
    lastposttime = scrapy.Field()
    newcartitle = scrapy.Field()
    newcarurl = scrapy.Field()
    img_url = scrapy.Field()
    first_owner = scrapy.Field()
    carno = scrapy.Field()
    carnotype = scrapy.Field()
    carddate = scrapy.Field()
    changecolor = scrapy.Field()
    outcolor = scrapy.Field()
    innercolor = scrapy.Field()
    desc = scrapy.Field()


class Che300Item(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    we_grab_time = scrapy.Field()
    parse_url = scrapy.Field()
    id = scrapy.Field()
    url = scrapy.Field()
    city = scrapy.Field()
    prov = scrapy.Field()
    title = scrapy.Field()
    car_desc = scrapy.Field()
    brand_id = scrapy.Field()
    brand_name = scrapy.Field()
    series_id = scrapy.Field()
    series_name = scrapy.Field()
    model_id = scrapy.Field()
    model_name = scrapy.Field()
    price = scrapy.Field()
    mile_age = scrapy.Field()
    register_date = scrapy.Field()
    reg_year = scrapy.Field()
    gear_type = scrapy.Field()
    color = scrapy.Field()
    liter = scrapy.Field()
    tel = scrapy.Field()
    tel_url = scrapy.Field()
    contactor = scrapy.Field()
    seller_type = scrapy.Field()
    dealer_id = scrapy.Field()
    dealer_name = scrapy.Field()
    car_source = scrapy.Field()
    car_status = scrapy.Field()
    post_time = scrapy.Field()
    grab_time = scrapy.Field()
    update_time = scrapy.Field()
    model_price = scrapy.Field()
    eval_price = scrapy.Field()
    vpr = scrapy.Field()
    match_step = scrapy.Field()
    sold_date = scrapy.Field()
    tlci_date = scrapy.Field()
    car_service = scrapy.Field()
    audit_date = scrapy.Field()
    next_year_eval_price = scrapy.Field()
    residual_value = scrapy.Field()
    qg_month = scrapy.Field()
    qg_mile = scrapy.Field()
    cr_day = scrapy.Field()
    qa_flag = scrapy.Field()
    qa_price = scrapy.Field()
    inspected = scrapy.Field()
    weight = scrapy.Field()
    is_trusted = scrapy.Field()
    match_rate = scrapy.Field()
    series_level = scrapy.Field()
    series_level_gid = scrapy.Field()
    liter_value = scrapy.Field()
    gear_type_value = scrapy.Field()
    liter_turbo = scrapy.Field()
    city_name = scrapy.Field()
    filter_discharge_standard = scrapy.Field()
    drive_type = scrapy.Field()
    maker_type = scrapy.Field()
    fuel_type = scrapy.Field()
    seat_number_code = scrapy.Field()
    price_reduce_offset = scrapy.Field()
    price_reduce_rate = scrapy.Field()
    price_reduce_count = scrapy.Field()
    re_eval = scrapy.Field()
    duplicated = scrapy.Field()
    source_name = scrapy.Field()
    fee_rate = scrapy.Field()
    fee_floor = scrapy.Field()
    fee_ceiling = scrapy.Field()
    enable_contact = scrapy.Field()
    transfer_time = scrapy.Field()
    aux_detail = scrapy.Field()
    modelInfo = scrapy.Field()
    all_content = scrapy.Field()


class autohome(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    familyid = scrapy.Field()
    guideprice_range = scrapy.Field()
    familyname = scrapy.Field()
    level = scrapy.Field()
    body_structure = scrapy.Field()
    engine = scrapy.Field()
    geartype = scrapy.Field()
    autohomeid = scrapy.Field()
    salesdesc = scrapy.Field()
    guideprice = scrapy.Field()
    salestatus = scrapy.Field()
    brandid = scrapy.Field()
    brandname = scrapy.Field()
    endurance_mileage = scrapy.Field()
    electromotor = scrapy.Field()
    charging_time = scrapy.Field()


class dongchedi2(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    brand_id = scrapy.Field()
    brand = scrapy.Field()
    series_id = scrapy.Field()
    dealer_max_price = scrapy.Field()
    dealer_min_price = scrapy.Field()
    series_name = scrapy.Field()
    title = scrapy.Field()
    content = scrapy.Field()
    behot_time = scrapy.Field()
    comment_count = scrapy.Field()
    read_count = scrapy.Field()
    digg_count = scrapy.Field()
    name = scrapy.Field()
    luoche_price = scrapy.Field()
    buy_city = scrapy.Field()
    oil = scrapy.Field()
    post_time = scrapy.Field()
    car_id = scrapy.Field()
    display_car_name = scrapy.Field()
    duration_desc = scrapy.Field()
    bought_time_desc = scrapy.Field()


class dongchedi(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    series = scrapy.Field()
    title = scrapy.Field()
    content = scrapy.Field()
    behot_time = scrapy.Field()
    comment_count = scrapy.Field()
    read_count = scrapy.Field()
    digg_count = scrapy.Field()
    name = scrapy.Field()
    display_car_name = scrapy.Field()
    duration_desc = scrapy.Field()
    bought_time_desc = scrapy.Field()


class autohome_img(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    series_id = scrapy.Field()
    series_name = scrapy.Field()
    brand_id = scrapy.Field()
    brand_name = scrapy.Field()
    img = scrapy.Field()


class NiuNiu_item(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    post_time = scrapy.Field()
    salesdesc = scrapy.Field()
    price = scrapy.Field()
    guide_price = scrapy.Field()
    procedure = scrapy.Field()
    area = scrapy.Field()
    remark = scrapy.Field()
    appearance = scrapy.Field()
    specification = scrapy.Field()
    merchant = scrapy.Field()
    brand = scrapy.Field()
    deal_sum = scrapy.Field()
    car_explain = scrapy.Field()
    configuration = scrapy.Field()


class CheHang168_item(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    post_time = scrapy.Field()
    brand = scrapy.Field()
    series_name = scrapy.Field()
    family_name = scrapy.Field()
    salesdesc = scrapy.Field()
    price = scrapy.Field()
    guide_price = scrapy.Field()
    store = scrapy.Field()
    chengjiao_number = scrapy.Field()
    car_location = scrapy.Field()
    # 规格
    specification = scrapy.Field()
    remark = scrapy.Field()
    car_id = scrapy.Field()


class KaiXinItem(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    brand_code = scrapy.Field()
    brand = scrapy.Field()
    modelId = scrapy.Field()
    model = scrapy.Field()
    carid = scrapy.Field()
    car_name = scrapy.Field()
    transaction_price = scrapy.Field()
    deal_time = scrapy.Field()
    gearbox = scrapy.Field()
    mileage = scrapy.Field()
    registeryear = scrapy.Field()
    yearchecktime = scrapy.Field()
    city = scrapy.Field()
    url = scrapy.Field()


class AutohomeItem(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    autohomeid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    makeyear = scrapy.Field()

    # new add
    vehicle_dimensions = scrapy.Field()
    producestatus = scrapy.Field()
    brandid = scrapy.Field()
    factoryid = scrapy.Field()
    brandname = scrapy.Field()
    factoryname = scrapy.Field()
    nation = scrapy.Field()
    property = scrapy.Field()

    # basic config
    level = scrapy.Field()
    vehicle_warranty = scrapy.Field()
    bodystyle = scrapy.Field()
    salesdesc = scrapy.Field()
    masspeed = scrapy.Field()
    price = scrapy.Field()
    output = scrapy.Field()

    accelerate = scrapy.Field()
    petrol_test = scrapy.Field()
    accelerate_test = scrapy.Field()
    petrol = scrapy.Field()
    ground_distance_test = scrapy.Field()
    engine = scrapy.Field()
    brake_test = scrapy.Field()

    # car body 车身
    length = scrapy.Field()
    baggage = scrapy.Field()
    seats = scrapy.Field()
    min_ground_distance = scrapy.Field()
    doors = scrapy.Field()
    frontgauge = scrapy.Field()
    heigh = scrapy.Field()
    wheelbase = scrapy.Field()
    backgauge = scrapy.Field()
    weigth = scrapy.Field()
    width = scrapy.Field()
    fulevolumn = scrapy.Field()

    # engine 发动机
    fuelmethod = scrapy.Field()
    maxtorque = scrapy.Field()
    maxrpm = scrapy.Field()
    maxps = scrapy.Field()
    fuelnumber = scrapy.Field()
    fueltype = scrapy.Field()
    strokemm = scrapy.Field()
    lwvnumber = scrapy.Field()
    valve = scrapy.Field()
    valve_mechanism = scrapy.Field()
    emission = scrapy.Field()
    boremm = scrapy.Field()
    maxpower = scrapy.Field()
    engine_technology = scrapy.Field()
    lwv = scrapy.Field()
    method = scrapy.Field()
    maxnm = scrapy.Field()
    cylinder_material = scrapy.Field()
    compress = scrapy.Field()
    engine_type = scrapy.Field()
    cylinder = scrapy.Field()
    head_port = scrapy.Field()

    # 变速箱
    geartype = scrapy.Field()
    gear = scrapy.Field()
    gearnumber = scrapy.Field()
    geardesc = scrapy.Field()

    # 底盘转向
    body_structure = scrapy.Field()
    backhang = scrapy.Field()
    driveway = scrapy.Field()
    fronthang = scrapy.Field()
    assistanttype = scrapy.Field()

    # 车轮制动
    parking_brake_type = scrapy.Field()
    frontbrake = scrapy.Field()
    backbrake = scrapy.Field()
    sparewheel = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()

    # PART II
    # 安全装备
    front_back_head_airbag = scrapy.Field()
    central_lock = scrapy.Field()
    keyless_start_system = scrapy.Field()
    safety_belt_is_not_prompt = scrapy.Field()
    engine_electronic_control_unit = scrapy.Field()
    remote_control_key = scrapy.Field()
    zero_tire_pressure = scrapy.Field()
    isofix_child_seat_interface = scrapy.Field()
    knee_airbag = scrapy.Field()
    driver_codrive_airbag = scrapy.Field()
    pke = scrapy.Field()
    tire_pressure_monitoring = scrapy.Field()
    front_back_side_airbag = scrapy.Field()

    # 操控配置
    brake_assist_eba_bas_ba = scrapy.Field()
    hill_descent_control = scrapy.Field()
    back_vaq = scrapy.Field()
    vehicle_stability_control_esp_dsc_vsc = scrapy.Field()
    aimatic = scrapy.Field()
    front_vaq = scrapy.Field()
    hill_start_assist = scrapy.Field()
    braking_force_distribution_ebd_cbc = scrapy.Field()
    variable_suspension = scrapy.Field()
    automatic_parking = scrapy.Field()
    limited_slip_differential = scrapy.Field()
    variable_gear_steering_ratio = scrapy.Field()
    traction_control_system_asr_tcs_trc = scrapy.Field()
    abs_antilock = scrapy.Field()

    # 外部配置
    induction_trunk = scrapy.Field()
    electric_sunroof = scrapy.Field()
    hubtype = scrapy.Field()
    panoramic_sunroof = scrapy.Field()
    electric_trunk = scrapy.Field()
    sliding_door = scrapy.Field()
    sport_appearance_suite = scrapy.Field()
    roof_rack = scrapy.Field()
    electric_door = scrapy.Field()

    # 内部配置
    computer_screen_of_driving = scrapy.Field()
    steering_wheel_shift = scrapy.Field()
    lhz = scrapy.Field()
    backing_radar = scrapy.Field()
    leather_steering_wheel = scrapy.Field()
    steering_wheel_adjustment = scrapy.Field()
    rear_video_monitor = scrapy.Field()
    memory_code = scrapy.Field()
    steering_wheel_electric_adjustment = scrapy.Field()
    cruise_control = scrapy.Field()
    multi_function_steering_wheel = scrapy.Field()
    lcd_panel = scrapy.Field()
    heads_up_display = scrapy.Field()

    # 座椅配置
    sports_seats = scrapy.Field()
    adjustable_seat_height = scrapy.Field()
    third_row_seats = scrapy.Field()
    rear_seat_electric_adjustment = scrapy.Field()
    leather_seats = scrapy.Field()
    adjustable_rear_row_backrest_angle = scrapy.Field()
    rear_seat_down = scrapy.Field()
    rear_row_seat_movement = scrapy.Field()
    seat_armrest = scrapy.Field()
    driver_seat_electric_adjustment = scrapy.Field()
    rear_row_hang_cup = scrapy.Field()
    front_back_seat_heating = scrapy.Field()
    seat_ventilation = scrapy.Field()
    electric_chair_memory = scrapy.Field()
    adjustable_lumbar_support = scrapy.Field()
    massage_seat = scrapy.Field()
    adjustable_shoulder_support = scrapy.Field()

    # 多媒体配置
    mp3_audio_support = scrapy.Field()
    bluetooth_car_phone = scrapy.Field()
    speakers_number = scrapy.Field()
    speaker_brand = scrapy.Field()
    rear_lcd_screen = scrapy.Field()
    gps_navigation = scrapy.Field()
    power_supply = scrapy.Field()
    single_cd_player = scrapy.Field()
    onboard_tv = scrapy.Field()
    external_audio_source_connectors = scrapy.Field()
    interactive_location_services = scrapy.Field()
    color_screen_display_control = scrapy.Field()

    # 灯光配置
    steering_headlights = scrapy.Field()
    Headlights_full = scrapy.Field()
    inside_atmosphere_lights = scrapy.Field()
    adjustable_headlight_height = scrapy.Field()
    headlight_cleaning_device = scrapy.Field()
    antifog_ligths = scrapy.Field()
    automatic_headlights = scrapy.Field()
    daytime__lights = scrapy.Field()
    Headlights_dipped = scrapy.Field()
    adaptive_light_distance = scrapy.Field()
    corner_lamp = scrapy.Field()

    # 玻璃/后视镜
    rearview_mirror_electric_folding = scrapy.Field()
    rearview_mirror_memory = scrapy.Field()
    window_clip_hand_safety = scrapy.Field()
    rearview_mirror_electric_adjustment = scrapy.Field()
    visor__mirror = scrapy.Field()
    back_privacy_glass = scrapy.Field()
    rearview_mirror_auto_anti_glare = scrapy.Field()
    backglass_sunshade = scrapy.Field()
    windshield_wiper_sensor = scrapy.Field()
    rear_windshield_wiper = scrapy.Field()
    insulating_glass = scrapy.Field()
    backsideglass_sunshade = scrapy.Field()
    rearview_mirror_heating = scrapy.Field()
    front_rear_lectric_windows = scrapy.Field()

    # 空调/冰箱
    zone_temperature_control = scrapy.Field()
    rear_ac = scrapy.Field()
    car_refrigerator = scrapy.Field()
    rear_independent_ac = scrapy.Field()
    ac_pollen_filter = scrapy.Field()
    auto_ac = scrapy.Field()

    # 高科技配置
    park_assist = scrapy.Field()
    doubling_asisst = scrapy.Field()
    night_vision = scrapy.Field()
    ldws = scrapy.Field()
    adaptive_cruise = scrapy.Field()
    panoramic_camera = scrapy.Field()
    lcd_screen_display_control = scrapy.Field()
    engine_start_stop = scrapy.Field()
    abls = scrapy.Field()
    active_front_steering = scrapy.Field()
    datasave = scrapy.Field()


class CarHome_Item(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    datasave = scrapy.Field()
    imgurl = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    brandname = scrapy.Field()
    seriesname = scrapy.Field()
    seriesid = scrapy.Field()
    subcateid = scrapy.Field()
    subcatename = scrapy.Field()
    shortdesc = scrapy.Field()
    status = scrapy.Field()
    price = scrapy.Field()
    driving = scrapy.Field()
    maxpower = scrapy.Field()
    emissionstandard = scrapy.Field()
    model = scrapy.Field()
    placeorigin = scrapy.Field()
    tonlevel = scrapy.Field()
    enginebrand = scrapy.Field()
    lwvnumber = scrapy.Field()
    fueltype = scrapy.Field()
    lwv = scrapy.Field()
    emission = scrapy.Field()
    maxwork = scrapy.Field()
    cab = scrapy.Field()
    Bridgesuspension = scrapy.Field()
    seatrows = scrapy.Field()
    mainseat = scrapy.Field()
    skylight = scrapy.Field()
    tiresnumber = scrapy.Field()
    ABS = scrapy.Field()
    ASR = scrapy.Field()
    fairing = scrapy.Field()
    airconditioner = scrapy.Field()
    powerwindow = scrapy.Field()
    electricrearview = scrapy.Field()
    musicapi = scrapy.Field()
    radio = scrapy.Field()
    qfoglight = scrapy.Field()
    nightlight = scrapy.Field()
    remotekey = scrapy.Field()
    Electroniclock = scrapy.Field()
    cruisecontrol = scrapy.Field()
    engine = scrapy.Field()
    gearbox = scrapy.Field()
    Rearaxleratio = scrapy.Field()
    carlong = scrapy.Field()
    carwidth = scrapy.Field()
    carhigh = scrapy.Field()
    carweight = scrapy.Field()
    totalweight = scrapy.Field()
    maxspeed = scrapy.Field()
    output = scrapy.Field()
    maxnm = scrapy.Field()
    technicalroute = scrapy.Field()
    qgears = scrapy.Field()
    hgears = scrapy.Field()
    tyresize = scrapy.Field()
    hbridge = scrapy.Field()
    qbridge = scrapy.Field()
    hbridgespeed = scrapy.Field()
    saddle = scrapy.Field()
    hwheelbrake = scrapy.Field()
    qwheelbrake = scrapy.Field()
    carid = scrapy.Field()


class Che300_Big_Car_Item(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    brand_id = scrapy.Field()
    brand_name = scrapy.Field()
    series_id = scrapy.Field()
    series_name = scrapy.Field()
    model_id = scrapy.Field()
    model_name = scrapy.Field()
    price = scrapy.Field()
    discharge_standard = scrapy.Field()
    liter = scrapy.Field()
    car_type = scrapy.Field()
    max_year = scrapy.Field()
    min_year = scrapy.Field()
    gonggao_type = scrapy.Field()
    type = scrapy.Field()
    driver = scrapy.Field()
    wheel = scrapy.Field()
    long = scrapy.Field()
    width = scrapy.Field()
    hight = scrapy.Field()
    qwheelbase = scrapy.Field()
    hwheelbase = scrapy.Field()
    weight = scrapy.Field()
    load = scrapy.Field()
    zong_weight = scrapy.Field()
    speed = scrapy.Field()
    production = scrapy.Field()
    overhang = scrapy.Field()
    angle = scrapy.Field()
    overturn = scrapy.Field()
    ton_level = scrapy.Field()
    manufacturers = scrapy.Field()
    guide_price = scrapy.Field()
    traction = scrapy.Field()
    engine = scrapy.Field()
    lwvnumber = scrapy.Field()
    fueltype = scrapy.Field()
    maxpower = scrapy.Field()
    output = scrapy.Field()
    emission = scrapy.Field()
    maxps = scrapy.Field()
    nm = scrapy.Field()
    maxnm = scrapy.Field()
    rated_speed = scrapy.Field()
    Engine_form = scrapy.Field()
    output_ml = scrapy.Field()
    box_long = scrapy.Field()
    box_width = scrapy.Field()
    box_high = scrapy.Field()
    box_type = scrapy.Field()
    people_num = scrapy.Field()
    seat_number = scrapy.Field()
    cage = scrapy.Field()
    Transmissions = scrapy.Field()
    qFil_number = scrapy.Field()
    hFil_number = scrapy.Field()
    shift_gear = scrapy.Field()
    tires_num = scrapy.Field()
    tires_specifications = scrapy.Field()
    Brake_form = scrapy.Field()
    tank = scrapy.Field()
    tank_texture = scrapy.Field()
    Rear_description = scrapy.Field()
    rear_speed = scrapy.Field()
    spring_num = scrapy.Field()
    suspension_type = scrapy.Field()
    chassis_type = scrapy.Field()
    frame = scrapy.Field()
    clutch = scrapy.Field()
    endurance_mileage = scrapy.Field()
    battery_capacity = scrapy.Field()
    url = scrapy.Field()


class Wo_Niu_Car_Item(scrapy.Item):
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    model = scrapy.Field()
    brand = scrapy.Field()
    series = scrapy.Field()
    boxLen = scrapy.Field()
    description = scrapy.Field()
    driveId = scrapy.Field()
    driveName = scrapy.Field()
    emissionId = scrapy.Field()
    emissionName = scrapy.Field()
    id = scrapy.Field()
    lowPrice = scrapy.Field()
    oilType = scrapy.Field()
    oilTypeName = scrapy.Field()
    power = scrapy.Field()
    price = scrapy.Field()
    volume = scrapy.Field()
    # url =scrapy.Field()
    # url =scrapy.Field()
    # url =scrapy.Field()
    # url =scrapy.Field()
    # url =scrapy.Field()


class Che300_Big_Car_evaluate_Item(scrapy.Item):
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    brand_id = scrapy.Field()
    series_id = scrapy.Field()
    model_id = scrapy.Field()
    prov_id = scrapy.Field()
    city_id = scrapy.Field()
    mile = scrapy.Field()
    reg_date = scrapy.Field()
    default_car_condition = scrapy.Field()
    good_dealer_high_buy_price = scrapy.Field()
    good_dealer_low_buy_price = scrapy.Field()
    good_dealer_high_sold_price = scrapy.Field()
    good_dealer_buy_price = scrapy.Field()
    good_dealer_low_sold_price = scrapy.Field()
    good_dealer_sold_price = scrapy.Field()
    excellent_dealer_high_buy_price = scrapy.Field()
    excellent_dealer_low_buy_price = scrapy.Field()
    excellent_dealer_high_sold_price = scrapy.Field()
    excellent_dealer_buy_price = scrapy.Field()
    excellent_dealer_sold_price = scrapy.Field()
    excellent_dealer_low_sold_price = scrapy.Field()
    normal_dealer_high_buy_price = scrapy.Field()
    normal_dealer_low_buy_price = scrapy.Field()
    normal_dealer_high_sold_price = scrapy.Field()
    normal_dealer_buy_price = scrapy.Field()
    normal_dealer_low_sold_price = scrapy.Field()
    normal_dealer_sold_price = scrapy.Field()
    goods_type = scrapy.Field()


class Woniu_Car_evaluate_Item(scrapy.Item):
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    brand = scrapy.Field()
    buyDate = scrapy.Field()
    city = scrapy.Field()
    drive = scrapy.Field()
    emission = scrapy.Field()
    model = scrapy.Field()
    oiltype = scrapy.Field()
    power = scrapy.Field()
    price = scrapy.Field()
    province = scrapy.Field()
    residueRatio = scrapy.Field()
    series = scrapy.Field()
    boxLen = scrapy.Field()
    volume = scrapy.Field()
    badMerchantPrice = scrapy.Field()
    midMerchantPrice = scrapy.Field()
    fineMerchantPrice = scrapy.Field()
    finePersonPrice = scrapy.Field()
    midPersonPrice = scrapy.Field()
    badPersonPrice = scrapy.Field()
    fineOldTruckPrice = scrapy.Field()
    badOldTruckPrice = scrapy.Field()
    midOldTruckPrice = scrapy.Field()
    seepName = scrapy.Field()
    seecName = scrapy.Field()
    description = scrapy.Field()


class YouKa_Car_Item(scrapy.Item):
    grab_time = scrapy.Field()
    url = scrapy.Field()
    brand = scrapy.Field()
    buyDate = scrapy.Field()
    city = scrapy.Field()
    drive = scrapy.Field()
    emission = scrapy.Field()
    model = scrapy.Field()
    oiltype = scrapy.Field()
    power = scrapy.Field()
    price = scrapy.Field()
    province = scrapy.Field()
    mileage = scrapy.Field()
    series = scrapy.Field()
    fineMapretailPrice = scrapy.Field()
    fineMapbuyPrice = scrapy.Field()
    ordinaryMapretailPrice = scrapy.Field()
    ordinaryMapbuyPrice = scrapy.Field()
    goodMaperetailPrice = scrapy.Field()
    goodMapbuyPrice = scrapy.Field()
    statusplus = scrapy.Field()


class Che300(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    grabtime = scrapy.Field()
    url = scrapy.Field()
    price1 = scrapy.Field()
    price2 = scrapy.Field()
    price3 = scrapy.Field()
    price4 = scrapy.Field()
    price5 = scrapy.Field()
    price6 = scrapy.Field()
    price7 = scrapy.Field()
    brand = scrapy.Field()
    series = scrapy.Field()
    salesdescid = scrapy.Field()
    regDate = scrapy.Field()
    cityid = scrapy.Field()
    prov = scrapy.Field()
    mile = scrapy.Field()
    car_md5 = scrapy.Field()
    statusplus = scrapy.Field()


class SouHu(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    carid = scrapy.Field()
    grabtime = scrapy.Field()
    url = scrapy.Field()
    brand = scrapy.Field()
    brandid = scrapy.Field()
    factory = scrapy.Field()
    factoryid = scrapy.Field()
    serialName = scrapy.Field()
    sellStatus = scrapy.Field()
    serialId = scrapy.Field()
    serialLevel = scrapy.Field()
    autoType = scrapy.Field()
    guidePrice = scrapy.Field()
    shortdesc = scrapy.Field()
    city_low_price = scrapy.Field()
    nearby_city_price = scrapy.Field()
    body = scrapy.Field()
    drivertype = scrapy.Field()
    engine = scrapy.Field()
    changing_box = scrapy.Field()
    oil_wear = scrapy.Field()
    baoyang_week = scrapy.Field()
    baoyang_price = scrapy.Field()
    door = scrapy.Field()
    seat = scrapy.Field()
    enginetype = scrapy.Field()
    output = scrapy.Field()
    Airintake = scrapy.Field()
    fule = scrapy.Field()
    environmental = scrapy.Field()
    Transmissiontype = scrapy.Field()
    drive = scrapy.Field()
    statusplus = scrapy.Field()


class youka_prcie(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    id = scrapy.Field()
    createTime = scrapy.Field()
    truckTitle = scrapy.Field()
    truckDriveform = scrapy.Field()
    dayTag = scrapy.Field()
    truckPrice = scrapy.Field()
    truckAddress = scrapy.Field()
    contactMobile = scrapy.Field()
    provincesName = scrapy.Field()
    districtName = scrapy.Field()
    contactname = scrapy.Field()
    showmileage = scrapy.Field()
    motorName = scrapy.Field()
    oiltype = scrapy.Field()
    environment = scrapy.Field()
    bodylong = scrapy.Field()
    nature = scrapy.Field()
    type = scrapy.Field()
    color = scrapy.Field()
    insurance = scrapy.Field()
    year_check = scrapy.Field()
    city = scrapy.Field()
    ownership = scrapy.Field()
    brandName = scrapy.Field()
    seriesName = scrapy.Field()
    modelName = scrapy.Field()


class qichejie(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    car_id = scrapy.Field()
    shortdesc = scrapy.Field()
    guideprice = scrapy.Field()
    # 上牌时间
    registerdate = scrapy.Field()
    used = scrapy.Field()
    leave_factory_day = scrapy.Field()
    VINcode = scrapy.Field()
    output = scrapy.Field()
    fule = scrapy.Field()
    car_code = scrapy.Field()
    mileage = scrapy.Field()
    color = scrapy.Field()
    engine_code = scrapy.Field()
    power = scrapy.Field()
    registration = scrapy.Field()
    city = scrapy.Field()
    speed_type = scrapy.Field()
    seat = scrapy.Field()
    year_check = scrapy.Field()
    jiaoqiangxian = scrapy.Field()
    owner = scrapy.Field()
    bussiness = scrapy.Field()
    desc = scrapy.Field()
    post_time = scrapy.Field()


class shiqiao_prcie(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    brandid = scrapy.Field()
    brand = scrapy.Field()
    model = scrapy.Field()
    modelid = scrapy.Field()
    emission = scrapy.Field()
    power = scrapy.Field()
    gerrboxBrand = scrapy.Field()
    carid = scrapy.Field()
    styleBulletinModel = scrapy.Field()
    styleDisname = scrapy.Field()
    styleDriveMode = scrapy.Field()
    styleName = scrapy.Field()
    stylePurposeId = scrapy.Field()
    stylePurposeName = scrapy.Field()


class che58_big_car(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    brandid = scrapy.Field()
    seriesid = scrapy.Field()
    city = scrapy.Field()
    brand = scrapy.Field()
    series = scrapy.Field()
    price = scrapy.Field()
    title = scrapy.Field()
    shortdesc = scrapy.Field()
    mileage = scrapy.Field()
    des = scrapy.Field()
    img = scrapy.Field()
    load = scrapy.Field()
    yearcheck = scrapy.Field()
    makeyear = scrapy.Field()
    insurance1_date = scrapy.Field()
    poste_time = scrapy.Field()
    type = scrapy.Field()
    carid = scrapy.Field()


class AutohomeItem2(scrapy.Item):
    url = scrapy.Field()
    grabtime = scrapy.Field()
    website = scrapy.Field()
    status = scrapy.Field()
    autohomeid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    makeyear = scrapy.Field()
    # new add
    vehicle_dimensions = scrapy.Field()
    producestatus = scrapy.Field()
    brandid = scrapy.Field()
    factoryid = scrapy.Field()
    brandname = scrapy.Field()
    factoryname = scrapy.Field()
    nation = scrapy.Field()
    property = scrapy.Field()

    # basic config
    level = scrapy.Field()
    vehicle_warranty = scrapy.Field()
    bodystyle = scrapy.Field()
    salesdesc = scrapy.Field()
    masspeed = scrapy.Field()
    price = scrapy.Field()
    output = scrapy.Field()

    accelerate = scrapy.Field()
    petrol_test = scrapy.Field()
    accelerate_test = scrapy.Field()
    petrol = scrapy.Field()
    ground_distance_test = scrapy.Field()
    engine = scrapy.Field()
    brake_test = scrapy.Field()

    # car body 车身
    length = scrapy.Field()
    baggage = scrapy.Field()
    seats = scrapy.Field()
    min_ground_distance = scrapy.Field()
    doors = scrapy.Field()
    frontgauge = scrapy.Field()
    heigh = scrapy.Field()
    wheelbase = scrapy.Field()
    backgauge = scrapy.Field()
    weigth = scrapy.Field()
    width = scrapy.Field()
    fulevolumn = scrapy.Field()

    # engine 发动机
    fuelmethod = scrapy.Field()
    maxtorque = scrapy.Field()
    maxrpm = scrapy.Field()
    maxps = scrapy.Field()
    fuelnumber = scrapy.Field()
    fueltype = scrapy.Field()
    strokemm = scrapy.Field()
    lwvnumber = scrapy.Field()
    valve = scrapy.Field()
    valve_mechanism = scrapy.Field()
    emission = scrapy.Field()
    boremm = scrapy.Field()
    maxpower = scrapy.Field()
    engine_technology = scrapy.Field()
    lwv = scrapy.Field()
    method = scrapy.Field()
    maxnm = scrapy.Field()
    cylinder_material = scrapy.Field()
    compress = scrapy.Field()
    engine_type = scrapy.Field()
    cylinder = scrapy.Field()
    head_port = scrapy.Field()

    # 变速箱
    geartype = scrapy.Field()
    gear = scrapy.Field()
    gearnumber = scrapy.Field()
    geardesc = scrapy.Field()

    # 底盘转向
    body_structure = scrapy.Field()
    backhang = scrapy.Field()
    driveway = scrapy.Field()
    fronthang = scrapy.Field()
    assistanttype = scrapy.Field()

    # 车轮制动
    parking_brake_type = scrapy.Field()
    frontbrake = scrapy.Field()
    backbrake = scrapy.Field()
    sparewheel = scrapy.Field()
    frontwheel = scrapy.Field()
    backwheel = scrapy.Field()

    # PART II
    # 安全装备
    front_back_head_airbag = scrapy.Field()
    central_lock = scrapy.Field()
    keyless_start_system = scrapy.Field()
    safety_belt_is_not_prompt = scrapy.Field()
    engine_electronic_control_unit = scrapy.Field()
    remote_control_key = scrapy.Field()
    zero_tire_pressure = scrapy.Field()
    isofix_child_seat_interface = scrapy.Field()
    knee_airbag = scrapy.Field()
    driver_codrive_airbag = scrapy.Field()
    pke = scrapy.Field()
    tire_pressure_monitoring = scrapy.Field()
    front_back_side_airbag = scrapy.Field()

    # 操控配置
    brake_assist_eba_bas_ba = scrapy.Field()
    hill_descent_control = scrapy.Field()
    back_vaq = scrapy.Field()
    vehicle_stability_control_esp_dsc_vsc = scrapy.Field()
    aimatic = scrapy.Field()
    front_vaq = scrapy.Field()
    hill_start_assist = scrapy.Field()
    braking_force_distribution_ebd_cbc = scrapy.Field()
    variable_suspension = scrapy.Field()
    automatic_parking = scrapy.Field()
    limited_slip_differential = scrapy.Field()
    variable_gear_steering_ratio = scrapy.Field()
    traction_control_system_asr_tcs_trc = scrapy.Field()
    abs_antilock = scrapy.Field()

    # 外部配置
    induction_trunk = scrapy.Field()
    electric_sunroof = scrapy.Field()
    hubtype = scrapy.Field()
    panoramic_sunroof = scrapy.Field()
    electric_trunk = scrapy.Field()
    sliding_door = scrapy.Field()
    sport_appearance_suite = scrapy.Field()
    roof_rack = scrapy.Field()
    electric_door = scrapy.Field()

    # 内部配置
    computer_screen_of_driving = scrapy.Field()
    steering_wheel_shift = scrapy.Field()
    lhz = scrapy.Field()
    backing_radar = scrapy.Field()
    leather_steering_wheel = scrapy.Field()
    steering_wheel_adjustment = scrapy.Field()
    rear_video_monitor = scrapy.Field()
    memory_code = scrapy.Field()
    steering_wheel_electric_adjustment = scrapy.Field()
    cruise_control = scrapy.Field()
    multi_function_steering_wheel = scrapy.Field()
    lcd_panel = scrapy.Field()
    heads_up_display = scrapy.Field()

    # 座椅配置
    sports_seats = scrapy.Field()
    adjustable_seat_height = scrapy.Field()
    third_row_seats = scrapy.Field()
    rear_seat_electric_adjustment = scrapy.Field()
    leather_seats = scrapy.Field()
    adjustable_rear_row_backrest_angle = scrapy.Field()
    rear_seat_down = scrapy.Field()
    rear_row_seat_movement = scrapy.Field()
    seat_armrest = scrapy.Field()
    driver_seat_electric_adjustment = scrapy.Field()
    rear_row_hang_cup = scrapy.Field()
    front_back_seat_heating = scrapy.Field()
    seat_ventilation = scrapy.Field()
    electric_chair_memory = scrapy.Field()
    adjustable_lumbar_support = scrapy.Field()
    massage_seat = scrapy.Field()
    adjustable_shoulder_support = scrapy.Field()

    # 多媒体配置
    mp3_audio_support = scrapy.Field()
    bluetooth_car_phone = scrapy.Field()
    speakers_number = scrapy.Field()
    speaker_brand = scrapy.Field()
    rear_lcd_screen = scrapy.Field()
    gps_navigation = scrapy.Field()
    power_supply = scrapy.Field()
    single_cd_player = scrapy.Field()
    onboard_tv = scrapy.Field()
    external_audio_source_connectors = scrapy.Field()
    interactive_location_services = scrapy.Field()
    color_screen_display_control = scrapy.Field()

    # 灯光配置
    steering_headlights = scrapy.Field()
    Headlights_full = scrapy.Field()
    inside_atmosphere_lights = scrapy.Field()
    adjustable_headlight_height = scrapy.Field()
    headlight_cleaning_device = scrapy.Field()
    antifog_ligths = scrapy.Field()
    automatic_headlights = scrapy.Field()
    daytime__lights = scrapy.Field()
    Headlights_dipped = scrapy.Field()
    adaptive_light_distance = scrapy.Field()
    corner_lamp = scrapy.Field()

    # 玻璃/后视镜
    rearview_mirror_electric_folding = scrapy.Field()
    rearview_mirror_memory = scrapy.Field()
    window_clip_hand_safety = scrapy.Field()
    rearview_mirror_electric_adjustment = scrapy.Field()
    visor__mirror = scrapy.Field()
    back_privacy_glass = scrapy.Field()
    rearview_mirror_auto_anti_glare = scrapy.Field()
    backglass_sunshade = scrapy.Field()
    windshield_wiper_sensor = scrapy.Field()
    rear_windshield_wiper = scrapy.Field()
    insulating_glass = scrapy.Field()
    backsideglass_sunshade = scrapy.Field()
    rearview_mirror_heating = scrapy.Field()
    front_rear_lectric_windows = scrapy.Field()

    # 空调/冰箱
    zone_temperature_control = scrapy.Field()
    rear_ac = scrapy.Field()
    car_refrigerator = scrapy.Field()
    rear_independent_ac = scrapy.Field()
    ac_pollen_filter = scrapy.Field()
    auto_ac = scrapy.Field()

    # 高科技配置
    park_assist = scrapy.Field()
    doubling_asisst = scrapy.Field()
    night_vision = scrapy.Field()
    ldws = scrapy.Field()
    adaptive_cruise = scrapy.Field()
    panoramic_camera = scrapy.Field()
    lcd_screen_display_control = scrapy.Field()
    engine_start_stop = scrapy.Field()
    abls = scrapy.Field()
    active_front_steering = scrapy.Field()
    datasave = scrapy.Field()
    image_logo_url = scrapy.Field()
    time_to_market = scrapy.Field()


class shiqiao_Car(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    configs = scrapy.Field()
    carid = scrapy.Field()
    modelid = scrapy.Field()
    styleBulletinModel = scrapy.Field()
    mdfUsrId = scrapy.Field()
    purposeId = scrapy.Field()
    styleName = scrapy.Field()
    modelName = scrapy.Field()
    crtTm = scrapy.Field()
    brandid = scrapy.Field()
    crtUsrId = scrapy.Field()
    isTrailer = scrapy.Field()
    makeName = scrapy.Field()
    styleDisname = scrapy.Field()
    isOutest = scrapy.Field()


class autohome_newcar(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    configs = scrapy.Field()
    brandname = scrapy.Field()
    brandid = scrapy.Field()
    factoryname = scrapy.Field()
    factoryid = scrapy.Field()
    familyname = scrapy.Field()
    familyid = scrapy.Field()
    producestatus = scrapy.Field()
    model = scrapy.Field()
    autohomeid = scrapy.Field()
    shortdesc = scrapy.Field()
    guideprice = scrapy.Field()
    dealprice = scrapy.Field()
    color = scrapy.Field()
    innercolor = scrapy.Field()
    year = scrapy.Field()


class car45(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    price = scrapy.Field()
    shortdesc = scrapy.Field()
    mileage = scrapy.Field()
    year = scrapy.Field()
    rank = scrapy.Field()
    carid = scrapy.Field()
    used = scrapy.Field()
    Make = scrapy.Field()
    Model = scrapy.Field()
    Location = scrapy.Field()
    Transmission = scrapy.Field()
    SellingCondition = scrapy.Field()
    Colour = scrapy.Field()
    statusplus = scrapy.Field()


class carcheki(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    Model = scrapy.Field()
    price = scrapy.Field()
    shortdesc = scrapy.Field()
    mileage = scrapy.Field()
    year = scrapy.Field()
    rank = scrapy.Field()
    carid = scrapy.Field()
    Make = scrapy.Field()
    desc = scrapy.Field()
    post_time = scrapy.Field()
    REF_ID = scrapy.Field()
    Condition = scrapy.Field()
    BodyType = scrapy.Field()
    Colour = scrapy.Field()
    DriveType = scrapy.Field()
    Transmission = scrapy.Field()
    InteriorType = scrapy.Field()
    DoorCount = scrapy.Field()
    Fuel = scrapy.Field()
    DriveSetup = scrapy.Field()
    statusplus = scrapy.Field()


class AutohomeCustomPriceItem(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    username = scrapy.Field()
    autohomeid = scrapy.Field()
    userid = scrapy.Field()
    fapiao = scrapy.Field()
    car_model = scrapy.Field()
    guide_price = scrapy.Field()
    total_price = scrapy.Field()
    naked_price = scrapy.Field()
    tax = scrapy.Field()
    jiaoqiangxian = scrapy.Field()
    chechuanshui = scrapy.Field()
    shangyexian = scrapy.Field()
    shangpaifei = scrapy.Field()
    pay_mode = scrapy.Field()
    promotion_set = scrapy.Field()
    buy_date = scrapy.Field()
    buy_location = scrapy.Field()
    dealer = scrapy.Field()
    dealerid = scrapy.Field()
    tel = scrapy.Field()
    dealer_addr = scrapy.Field()
    star_level = scrapy.Field()
    service_level = scrapy.Field()
    cutting_skill = scrapy.Field()


class che58_newcar(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    brand_name = scrapy.Field()
    brand_id = scrapy.Field()
    serier_id = scrapy.Field()
    serier_name = scrapy.Field()
    factoty_name = scrapy.Field()
    factoty_id = scrapy.Field()
    stat = scrapy.Field()
    model_id = scrapy.Field()
    model_name = scrapy.Field()
    short_desc = scrapy.Field()
    Dealer_price = scrapy.Field()
    guide_price = scrapy.Field()
    speed = scrapy.Field()
    output = scrapy.Field()
    drive_type = scrapy.Field()
    doors = scrapy.Field()
    seat = scrapy.Field()
    air_inlet = scrapy.Field()
    fuel_type = scrapy.Field()
    body = scrapy.Field()
    makeyear = scrapy.Field()
    environment = scrapy.Field()


class che58_grade(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    series_id = scrapy.Field()
    serise_name = scrapy.Field()
    car_grade = scrapy.Field()
    grade = scrapy.Field()
    rank = scrapy.Field()
    impression = scrapy.Field()
    quality_score = scrapy.Field()
    charm_score = scrapy.Field()
    brand_score = scrapy.Field()
    exp_score = scrapy.Field()
    recom_score = scrapy.Field()


class AutohomeCustomPriceItem1(scrapy.Item):
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    autohomeid = scrapy.Field()
    Naked_car_price = scrapy.Field()
    owner_car_price = scrapy.Field()


class DongCheDi(scrapy.Item):
    factory = scrapy.Field()
    body = scrapy.Field()
    doors = scrapy.Field()
    seat = scrapy.Field()
    driver = scrapy.Field()
    speed = scrapy.Field()
    engine = scrapy.Field()
    car_body = scrapy.Field()
    output = scrapy.Field()
    air_type = scrapy.Field()
    environmental = scrapy.Field()
    brand_id = scrapy.Field()
    series_id = scrapy.Field()
    series_name = scrapy.Field()
    brand_name = scrapy.Field()
    shortdesc = scrapy.Field()
    price = scrapy.Field()
    makeyear = scrapy.Field()
    car_id = scrapy.Field()
    official_price = scrapy.Field()
    dealer_price = scrapy.Field()
    config = scrapy.Field()
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()


class DiyidiandongButieItem(scrapy.Item):
    grabtime = scrapy.Field()
    url = scrapy.Field()
    statusplus = scrapy.Field()
    serise_name = scrapy.Field()
    serise_id = scrapy.Field()
    brand_id = scrapy.Field()
    brand_name = scrapy.Field()
    factory_name = scrapy.Field()
    guide_price = scrapy.Field()
    butie_price = scrapy.Field()
    shortdesc = scrapy.Field()
    car_id = scrapy.Field()
    config = scrapy.Field()
    car_body = scrapy.Field()
    auto_driver = scrapy.Field()
    energy_type = scrapy.Field()
    door = scrapy.Field()
    seat = scrapy.Field()
    output = scrapy.Field()
    air_type = scrapy.Field()
    environment = scrapy.Field()
    driver = scrapy.Field()
    gongxibu = scrapy.Field()
    air_type = scrapy.Field()


class dongchedi3(scrapy.Item):
    # define the fields for your item here like:
    statusplus = scrapy.Field()
    grab_time = scrapy.Field()
    url = scrapy.Field()
    brand_id = scrapy.Field()
    brand = scrapy.Field()
    series_id = scrapy.Field()
    dealer_max_price = scrapy.Field()
    dealer_min_price = scrapy.Field()
    series_name = scrapy.Field()
    title = scrapy.Field()
    content = scrapy.Field()
    behot_time = scrapy.Field()
    comment_count = scrapy.Field()
    read_count = scrapy.Field()
    digg_count = scrapy.Field()
    name = scrapy.Field()
    display_car_name = scrapy.Field()
    duration_desc = scrapy.Field()
    bought_time_desc = scrapy.Field()
    luoche_price = scrapy.Field()
    oil = scrapy.Field()
    buy_city = scrapy.Field()
    post_time = scrapy.Field()
    car_id=scrapy.Field()



